# Form implementation generated from reading ui file 'convertor.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 112)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBoxTo = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBoxTo.setObjectName("comboBoxTo")
        self.gridLayout.addWidget(self.comboBoxTo, 1, 1, 1, 1)
        self.comboBoxFrom = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBoxFrom.setObjectName("comboBoxFrom")
        self.gridLayout.addWidget(self.comboBoxFrom, 0, 1, 1, 1)
        self.lineEditFrom = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditFrom.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly|QtCore.Qt.InputMethodHint.ImhFormattedNumbersOnly)
        self.lineEditFrom.setClearButtonEnabled(True)
        self.lineEditFrom.setObjectName("lineEditFrom")
        self.gridLayout.addWidget(self.lineEditFrom, 0, 0, 1, 1)
        self.lineEditTo = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditTo.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly|QtCore.Qt.InputMethodHint.ImhFormattedNumbersOnly)
        self.lineEditTo.setReadOnly(True)
        self.lineEditTo.setClearButtonEnabled(False)
        self.lineEditTo.setObjectName("lineEditTo")
        self.gridLayout.addWidget(self.lineEditTo, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 451, 21))
        self.menubar.setObjectName("menubar")
        self.menuCategory = QtWidgets.QMenu(parent=self.menubar)
        self.menuCategory.setObjectName("menuCategory")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDistance = QtGui.QAction(parent=MainWindow)
        self.actionDistance.setObjectName("actionDistance")
        self.actionAngle = QtGui.QAction(parent=MainWindow)
        self.actionAngle.setObjectName("actionAngle")
        self.actionPoids = QtGui.QAction(parent=MainWindow)
        self.actionPoids.setObjectName("actionPoids")
        self.actionDonnees = QtGui.QAction(parent=MainWindow)
        self.actionDonnees.setObjectName("actionDonnees")
        self.menubar.addAction(self.menuCategory.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Convertor"))
        self.menuCategory.setTitle(_translate("MainWindow", "Category"))
        self.actionDistance.setText(_translate("MainWindow", "Distance"))
        self.actionAngle.setText(_translate("MainWindow", "Angle"))
        self.actionPoids.setText(_translate("MainWindow", "Poids"))
        self.actionDonnees.setText(_translate("MainWindow", "Donnees"))
